# This code was automatically generated by CWrap version 0.0.0

cdef extern from "eNBSP/include/NBioAPI_IndexSearch.h":

    ctypedef signed char NBioAPI_SINT8

    ctypedef unsigned char NBioAPI_UINT8

    ctypedef short NBioAPI_SINT16

    ctypedef unsigned short NBioAPI_UINT16

    ctypedef int NBioAPI_SINT32

    ctypedef unsigned int NBioAPI_UINT32

    ctypedef long long NBioAPI_SINT64

    ctypedef unsigned long long NBioAPI_UINT64

    ctypedef long NBioAPI_SLONG

    ctypedef unsigned long NBioAPI_ULONG

    ctypedef double NBioAPI_DOUBLE

    ctypedef float NBioAPI_FLOAT

    ctypedef long NBioAPI_SINT

    ctypedef unsigned long NBioAPI_UINT

    ctypedef int NBioAPI_BOOL

    ctypedef char NBioAPI_CHAR

    ctypedef int NBioAPI_WCHAR

    ctypedef unsigned char NBioAPI_BYTE

    ctypedef NBioAPI_CHAR *NBioAPI_CHAR_PTR

    ctypedef NBioAPI_WCHAR *NBioAPI_WCHAR_PTR

    ctypedef NBioAPI_BYTE *NBioAPI_BYTE_PTR

    ctypedef NBioAPI_CHAR_PTR LPSTR

    ctypedef NBioAPI_CHAR CHAR

    ctypedef const char *LPCTSTR

    ctypedef void *HINSTANCE

    ctypedef NBioAPI_UINT32 NBioAPI_HWND

    ctypedef void *NBioAPI_VOID_PTR

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_VERSION

    cdef struct nbioapi_version:
        NBioAPI_UINT32 Major
        NBioAPI_UINT32 Minor

    ctypedef nbioapi_version NBioAPI_VERSION

    ctypedef nbioapi_version *NBioAPI_VERSION_PTR

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_DATA_TYPE

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_PURPOSE

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_QUALITY

    cdef struct nbioapi_fir_header:
        NBioAPI_UINT32 Length
        NBioAPI_UINT32 DataLength
        NBioAPI_FIR_VERSION Version
        NBioAPI_FIR_DATA_TYPE DataType
        NBioAPI_FIR_PURPOSE Purpose
        NBioAPI_FIR_QUALITY Quality
        NBioAPI_UINT32 Reserved

    ctypedef nbioapi_fir_header NBioAPI_FIR_HEADER

    ctypedef nbioapi_fir_header *NBioAPI_FIR_HEADER_PTR

    ctypedef NBioAPI_UINT8 NBioAPI_FIR_DATA

    ctypedef NBioAPI_UINT32 NBioAPI_FIR_FORMAT

    cdef struct nbioapi_fir:
        NBioAPI_FIR_FORMAT Format
        NBioAPI_FIR_HEADER Header
        NBioAPI_FIR_DATA *Data

    ctypedef nbioapi_fir NBioAPI_FIR

    ctypedef nbioapi_fir *NBioAPI_FIR_PTR

    cdef struct nbioapi_fir_payload:
        NBioAPI_UINT32 Length
        NBioAPI_UINT8 *Data

    ctypedef nbioapi_fir_payload NBioAPI_FIR_PAYLOAD

    ctypedef nbioapi_fir_payload *NBioAPI_FIR_PAYLOAD_PTR

    ctypedef NBioAPI_UINT NBioAPI_HANDLE

    ctypedef NBioAPI_UINT *NBioAPI_HANDLE_PTR

    ctypedef NBioAPI_UINT NBioAPI_FIR_HANDLE

    ctypedef NBioAPI_UINT *NBioAPI_FIR_HANDLE_PTR

    ctypedef NBioAPI_UINT32 NBioAPI_FIR_SECURITY_LEVEL

    cdef struct nbioapi_init_info_0:
        NBioAPI_UINT32 StructureType
        NBioAPI_UINT32 MaxFingersForEnroll
        NBioAPI_UINT32 SamplesPerFinger
        NBioAPI_UINT32 DefaultTimeout
        NBioAPI_UINT32 EnrollImageQuality
        NBioAPI_UINT32 VerifyImageQuality
        NBioAPI_UINT32 IdentifyImageQuality
        NBioAPI_FIR_SECURITY_LEVEL SecurityLevel

    ctypedef nbioapi_init_info_0 NBioAPI_INIT_INFO_0

    ctypedef nbioapi_init_info_0 *NBioAPI_INIT_INFO_PTR_0

    cdef struct nbioapi_init_info_1:
        NBioAPI_UINT32 StructureType
        NBioAPI_FIR_SECURITY_LEVEL SecurityLevelForEnroll
        NBioAPI_UINT32 NecessaryEnrollNum
        NBioAPI_UINT32 Reserved1
        NBioAPI_UINT32 Reserved2
        NBioAPI_UINT32 Reserved3
        NBioAPI_UINT32 Reserved4
        NBioAPI_UINT32 Reserved5
        NBioAPI_UINT32 Reserved6
        NBioAPI_UINT32 Reserved7

    ctypedef nbioapi_init_info_1 NBioAPI_INIT_INFO_1

    ctypedef nbioapi_init_info_1 *NBioAPI_INIT_INFO_PTR_1

    ctypedef NBioAPI_VOID_PTR NBioAPI_INIT_INFO_PTR

    cdef struct nbioapi_device_info_0:
        NBioAPI_UINT32 StructureType
        NBioAPI_UINT32 ImageWidth
        NBioAPI_UINT32 ImageHeight
        NBioAPI_UINT32 Brightness
        NBioAPI_UINT32 Contrast
        NBioAPI_UINT32 Gain

    ctypedef nbioapi_device_info_0 NBioAPI_DEVICE_INFO_0

    ctypedef nbioapi_device_info_0 *NBioAPI_DEVICE_INFO_PTR_0

    ctypedef NBioAPI_VOID_PTR NBioAPI_DEVICE_INFO_PTR

    ctypedef NBioAPI_UINT16 NBioAPI_DEVICE_ID

    ctypedef NBioAPI_UINT8 NBioAPI_DEVICE_NAME

    ctypedef NBioAPI_UINT32 NBioAPI_RETURN

    cdef struct nbioapi_fir_textencode:
        NBioAPI_BOOL IsWideChar
        NBioAPI_CHAR_PTR TextFIR

    ctypedef nbioapi_fir_textencode NBioAPI_FIR_TEXTENCODE

    ctypedef nbioapi_fir_textencode *NBioAPI_FIR_TEXTENCODE_PTR

    ctypedef NBioAPI_UINT8 NBioAPI_INPUT_FIR_FORM

    cdef union __nbioapi_input_fir_InputFIR:
        NBioAPI_FIR_HANDLE_PTR FIRinBSP
        NBioAPI_VOID_PTR FIR
        NBioAPI_FIR_TEXTENCODE_PTR TextFIR

    ctypedef __nbioapi_input_fir_InputFIR __nbioapi_input_fir_InputFIR_t

    cdef struct nbioapi_input_fir:
        NBioAPI_INPUT_FIR_FORM Form
        __nbioapi_input_fir_InputFIR_t InputFIR

    ctypedef nbioapi_input_fir NBioAPI_INPUT_FIR

    ctypedef nbioapi_input_fir *NBioAPI_INPUT_FIR_PTR

    ctypedef NBioAPI_UINT32 NBioAPI_WINDOW_STYLE

    cdef struct nbioapi_window_callback_param_ex:
        NBioAPI_UINT32 dwDeviceError
        NBioAPI_UINT32 dwReserved[8]
        NBioAPI_VOID_PTR lpReserved

    ctypedef nbioapi_window_callback_param_ex NBioAPI_WINDOW_CALLBACK_PARAM_EX

    ctypedef nbioapi_window_callback_param_ex *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_EX

    cdef struct nbioapi_window_callback_param_0:
        NBioAPI_UINT32 dwQuality
        NBioAPI_UINT8 *lpImageBuf
        NBioAPI_WINDOW_CALLBACK_PARAM_PTR_EX pParamEx

    ctypedef nbioapi_window_callback_param_0 NBioAPI_WINDOW_CALLBACK_PARAM_0

    ctypedef nbioapi_window_callback_param_0 *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_0

    cdef struct nbioapi_window_callback_param_1_1:
        NBioAPI_UINT32 dwStartTime
        NBioAPI_UINT32 dwCapTime
        NBioAPI_UINT32 dwEndTime
        NBioAPI_UINT32 Reserved1
        NBioAPI_UINT32 Reserved2
        NBioAPI_UINT32 Reserved3
        NBioAPI_UINT32 Reserved4
        NBioAPI_UINT32 Reserved5
        NBioAPI_UINT32 Reserved6
        NBioAPI_UINT32 Reserved7
        NBioAPI_UINT32 Reserved8
        NBioAPI_VOID_PTR lpReserved

    ctypedef nbioapi_window_callback_param_1_1 NBioAPI_WINDOW_CALLBACK_PARAM_1_1

    ctypedef nbioapi_window_callback_param_1_1 *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_1_1

    cdef struct nbioapi_window_callback_param_1:
        NBioAPI_UINT32 dwResult
        NBioAPI_WINDOW_CALLBACK_PARAM_PTR_1_1 lpCBParam1_1

    ctypedef nbioapi_window_callback_param_1 NBioAPI_WINDOW_CALLBACK_PARAM_1

    ctypedef nbioapi_window_callback_param_1 *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_1

    ctypedef unsigned int (*NBioAPI_WINDOW_CALLBACK_0)(nbioapi_window_callback_param_0 *, void *)

    ctypedef unsigned int (*NBioAPI_WINDOW_CALLBACK_1)(nbioapi_window_callback_param_1 *, void *)

    cdef struct nbioapi_callback_info_0:
        NBioAPI_UINT32 CallBackType
        NBioAPI_WINDOW_CALLBACK_0 CallBackFunction
        NBioAPI_VOID_PTR UserCallBackParam

    ctypedef nbioapi_callback_info_0 NBioAPI_CALLBACK_INFO_0

    ctypedef nbioapi_callback_info_0 *NBioAPI_CALLBACK_INFO_PTR_0

    cdef struct nbioapi_callback_info_1:
        NBioAPI_UINT32 CallBackType
        NBioAPI_WINDOW_CALLBACK_1 CallBackFunction
        NBioAPI_VOID_PTR UserCallBackParam

    ctypedef nbioapi_callback_info_1 NBioAPI_CALLBACK_INFO_1

    ctypedef nbioapi_callback_info_1 *NBioAPI_CALLBACK_INFO_PTR_1

    cdef struct nbioapi_window_option_2:
        NBioAPI_UINT8 FPForeColor[3]
        NBioAPI_UINT8 FPBackColor[3]
        NBioAPI_UINT8 DisableFingerForEnroll[10]
        NBioAPI_UINT32 Reserved1[4]
        NBioAPI_VOID_PTR Reserved2

    ctypedef nbioapi_window_option_2 NBioAPI_WINDOW_OPTION_2

    ctypedef nbioapi_window_option_2 *NBioAPI_WINDOW_OPTION_PTR_2

    cdef struct nbioapi_window_option:
        NBioAPI_UINT32 Length
        NBioAPI_WINDOW_STYLE WindowStyle
        NBioAPI_HWND ParentWnd
        NBioAPI_HWND FingerWnd
        NBioAPI_CALLBACK_INFO_0 CaptureCallBackInfo
        NBioAPI_CALLBACK_INFO_1 FinishCallBackInfo
        NBioAPI_CHAR_PTR CaptionMsg
        NBioAPI_CHAR_PTR CancelMsg
        NBioAPI_WINDOW_OPTION_PTR_2 Option2

    ctypedef nbioapi_window_option NBioAPI_WINDOW_OPTION

    ctypedef nbioapi_window_option *NBioAPI_WINDOW_OPTION_PTR

    cdef enum MINCONV_DATA_TYPE:
        MINCONV_TYPE_FDP
        MINCONV_TYPE_FDU
        MINCONV_TYPE_FDA
        MINCONV_TYPE_OLD_FDA
        MINCONV_TYPE_FDAC
        MINCONV_TYPE_FIM10_HV
        MINCONV_TYPE_FIM10_LV
        MINCONV_TYPE_FIM01_HV
        MINCONV_TYPE_FIM01_HD
        MINCONV_TYPE_FELICA
        MINCONV_TYPE_EXTENSION
        MINCONV_TYPE_TEMPLATESIZE_32
        MINCONV_TYPE_TEMPLATESIZE_48
        MINCONV_TYPE_TEMPLATESIZE_64
        MINCONV_TYPE_TEMPLATESIZE_80
        MINCONV_TYPE_TEMPLATESIZE_96
        MINCONV_TYPE_TEMPLATESIZE_112
        MINCONV_TYPE_TEMPLATESIZE_128
        MINCONV_TYPE_TEMPLATESIZE_144
        MINCONV_TYPE_TEMPLATESIZE_160
        MINCONV_TYPE_TEMPLATESIZE_176
        MINCONV_TYPE_TEMPLATESIZE_192
        MINCONV_TYPE_TEMPLATESIZE_208
        MINCONV_TYPE_TEMPLATESIZE_224
        MINCONV_TYPE_TEMPLATESIZE_240
        MINCONV_TYPE_TEMPLATESIZE_256
        MINCONV_TYPE_TEMPLATESIZE_272
        MINCONV_TYPE_TEMPLATESIZE_288
        MINCONV_TYPE_TEMPLATESIZE_304
        MINCONV_TYPE_TEMPLATESIZE_320
        MINCONV_TYPE_TEMPLATESIZE_336
        MINCONV_TYPE_TEMPLATESIZE_352
        MINCONV_TYPE_TEMPLATESIZE_368
        MINCONV_TYPE_TEMPLATESIZE_384
        MINCONV_TYPE_TEMPLATESIZE_400
        MINCONV_TYPE_ANSI
        MINCONV_TYPE_ISO
        MINCONV_TYPE_MAX

    ctypedef NBioAPI_UINT8 NBioAPI_FINGER_ID

    cdef struct nbioapi_match_option_0:
        NBioAPI_UINT8 StructureType
        NBioAPI_UINT8 NoMatchFinger[11]
        NBioAPI_UINT32 Reserved[8]

    ctypedef nbioapi_match_option_0 NBioAPI_MATCH_OPTION_0

    ctypedef nbioapi_match_option_0 *NBioAPI_MATCH_OPTION_PTR_0

    ctypedef NBioAPI_VOID_PTR NBioAPI_MATCH_OPTION_PTR

    ctypedef NBioAPI_UINT8 NBioAPI_QUALITY

    cdef struct nbioapi_quality_info_0:
        NBioAPI_UINT8 StructureType
        NBioAPI_QUALITY Quality[11][2]
        NBioAPI_UINT32 Reserved[4]

    ctypedef nbioapi_quality_info_0 NBioAPI_QUALITY_INFO_0

    ctypedef nbioapi_quality_info_0 *NBioAPI_QUALITY_INFO_PTR_0

    cdef struct nbioapi_quality_info_1:
        NBioAPI_UINT8 StructureType
        NBioAPI_UINT8 Quality[11][2]
        NBioAPI_UINT32 Reserved[4]

    ctypedef nbioapi_quality_info_1 NBioAPI_QUALITY_INFO_1

    ctypedef nbioapi_quality_info_1 *NBioAPI_QUALITY_INFO_PTR_1

    ctypedef NBioAPI_VOID_PTR NBioAPI_QUALITY_INFO_PTR

    cdef struct nbioapi_deviceinfoex:
        NBioAPI_DEVICE_ID NameID
        NBioAPI_UINT16 Instance
        NBioAPI_CHAR Name[64]
        NBioAPI_CHAR Description[256]
        NBioAPI_CHAR Dll[64]
        NBioAPI_CHAR Sys[64]
        NBioAPI_UINT32 AutoOn
        NBioAPI_UINT32 Brightness
        NBioAPI_UINT32 Contrast
        NBioAPI_UINT32 Gain
        NBioAPI_UINT32 Reserved[8]

    ctypedef nbioapi_deviceinfoex NBioAPI_DEVICE_INFO_EX

    ctypedef nbioapi_deviceinfoex *NBioAPI_DEVICE_INFO_EX_PTR

    cdef struct nbioapi_indexsearch_init_info_0:
        NBioAPI_UINT32 StructureType
        NBioAPI_UINT32 PresearchRate
        NBioAPI_UINT32 researved0
        NBioAPI_UINT32 researved1
        NBioAPI_UINT32 researved2
        NBioAPI_UINT32 researved3
        NBioAPI_UINT32 researved4
        NBioAPI_UINT32 researved5
        NBioAPI_UINT32 *researved6

    ctypedef nbioapi_indexsearch_init_info_0 NBioAPI_INDEXSEARCH_INIT_INFO_0

    ctypedef nbioapi_indexsearch_init_info_0 *NBioAPI_INDEXSEARCH_INIT_INFO_PTR_0

    cdef struct nbioapi_indexsearch_fp_info:
        NBioAPI_UINT32 ID
        NBioAPI_UINT8 FingerID
        NBioAPI_UINT8 SampleNumber

    ctypedef nbioapi_indexsearch_fp_info NBioAPI_INDEXSEARCH_FP_INFO

    ctypedef nbioapi_indexsearch_fp_info *NBioAPI_INDEXSEARCH_FP_INFO_PTR

    cdef struct nbioapi_indexsearch_sample_info:
        NBioAPI_UINT32 ID
        NBioAPI_UINT8 SampleCount[11]

    ctypedef nbioapi_indexsearch_sample_info NBioAPI_INDEXSEARCH_SAMPLE_INFO

    ctypedef nbioapi_indexsearch_sample_info *NBioAPI_INDEXSEARCH_SAMPLE_INFO_PTR

    cdef struct nbioapi_indexsearch_callback_param_0:
        NBioAPI_UINT32 TotalCount
        NBioAPI_UINT32 ProgressPos
        NBioAPI_INDEXSEARCH_FP_INFO FpInfo
        NBioAPI_UINT32 Reserved0
        NBioAPI_UINT32 Reserved1
        NBioAPI_UINT32 Reserved2
        NBioAPI_UINT32 Reserved3
        NBioAPI_VOID_PTR Reserved4

    ctypedef nbioapi_indexsearch_callback_param_0 NBioAPI_INDEXSEARCH_CALLBACK_PARAM_0

    ctypedef nbioapi_indexsearch_callback_param_0 *NBioAPI_INDEXSEARCH_CALLBACK_PARAM_PTR_0

    ctypedef unsigned int (*NBioAPI_INDEXSEARCH_CALLBACK_0)(nbioapi_indexsearch_callback_param_0 *, void *)

    cdef struct nbioapi_indexsearch_callback_info_0:
        NBioAPI_UINT32 CallBackType
        NBioAPI_INDEXSEARCH_CALLBACK_0 CallBackFunction
        NBioAPI_VOID_PTR UserCallBackParam

    ctypedef nbioapi_indexsearch_callback_info_0 NBioAPI_INDEXSEARCH_CALLBACK_INFO_0

    ctypedef nbioapi_indexsearch_callback_info_0 *NBioAPI_INDEXSEARCH_CALLBACK_INFO_PTR_0

    NBioAPI_RETURN NBioAPI_InitIndexSearchEngine(NBioAPI_HANDLE hHandle)

    NBioAPI_RETURN NBioAPI_TerminateIndexSearchEngine(NBioAPI_HANDLE hHandle)

    NBioAPI_RETURN NBioAPI_SetIndexSearchInitInfo(NBioAPI_HANDLE hHandle, NBioAPI_UINT8 nStructureType, NBioAPI_INIT_INFO_PTR pInitInfo)

    NBioAPI_RETURN NBioAPI_GetIndexSearchInitInfo(NBioAPI_HANDLE hHandle, NBioAPI_UINT8 nStructureType, NBioAPI_INIT_INFO_PTR pInitInfo)

    NBioAPI_RETURN NBioAPI_AddFIRToIndexSearchDB(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR pInputFIR, NBioAPI_UINT32 nUserID, NBioAPI_INDEXSEARCH_SAMPLE_INFO_PTR pSampleInfo)

    NBioAPI_RETURN NBioAPI_RemoveDataFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo)

    NBioAPI_RETURN NBioAPI_RemoveUserFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_UINT32 nUserID)

    NBioAPI_RETURN NBioAPI_IdentifyDataFromIndexSearchDB(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR pInputFIR, NBioAPI_FIR_SECURITY_LEVEL nSecuLevel, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo, NBioAPI_INDEXSEARCH_CALLBACK_INFO_PTR_0 pCallbackInfo0)

    NBioAPI_RETURN NBioAPI_IdentifyDataFromIndexSearchDBEx(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR pInputFIR, NBioAPI_FIR_SECURITY_LEVEL nSecuLevel, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo, NBioAPI_INDEXSEARCH_CALLBACK_INFO_PTR_0 pCallbackInfo0)

    NBioAPI_RETURN NBioAPI_ClearIndexSearchDB(NBioAPI_HANDLE hHandle)

    NBioAPI_RETURN NBioAPI_SaveIndexSearchDBToFile(NBioAPI_HANDLE hHandle, const NBioAPI_CHAR *szFilepath)

    NBioAPI_RETURN NBioAPI_LoadIndexSearchDBFromFile(NBioAPI_HANDLE hHandle, const NBioAPI_CHAR *szFilepath)

    NBioAPI_RETURN NBioAPI_GetDataCountFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_UINT32 *pDataCount)

    NBioAPI_RETURN NBioAPI_CheckDataExistFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo, NBioAPI_BOOL *pExist)

    ctypedef unsigned int (*FP_NBioAPI_InitIndexSearchEngine)(unsigned long)

    ctypedef unsigned int (*FP_NBioAPI_TerminateIndexSearchEngine)(unsigned long)

    ctypedef unsigned int (*FP_NBioAPI_SetIndexSearchInitInfo)(unsigned long, unsigned char, void *)

    ctypedef unsigned int (*FP_NBioAPI_GetIndexSearchInitInfo)(unsigned long, unsigned char, void *)

    ctypedef unsigned int (*FP_NBioAPI_AddFIRToIndexSearchDB)(unsigned long, nbioapi_input_fir *, unsigned int, nbioapi_indexsearch_sample_info *)

    ctypedef unsigned int (*FP_NBioAPI_RemoveDataFromIndexSearchDB)(unsigned long, nbioapi_indexsearch_fp_info *)

    ctypedef unsigned int (*FP_NBioAPI_RemoveUserFromIndexSearchDB)(unsigned long, unsigned int)

    ctypedef unsigned int (*FP_NBioAPI_IdentifyDataFromIndexSearchDB)(unsigned long, nbioapi_input_fir *, unsigned int, nbioapi_indexsearch_fp_info *, nbioapi_indexsearch_callback_info_0 *)

    ctypedef unsigned int (*FP_NBioAPI_ClearIndexSearchDB)(unsigned long)

    ctypedef unsigned int (*FP_NBioAPI_SaveIndexSearchDBToFile)(unsigned long, const char *)

    ctypedef unsigned int (*FP_NBioAPI_LoadIndexSearchDBFromFile)(unsigned long, const char *)

    ctypedef unsigned int (*FP_NBioAPI_GetDataCountFromIndexSearchDB)(unsigned long, unsigned int *)

    ctypedef unsigned int (*FP_NBioAPI_CheckDataExistFromIndexSearchDB)(unsigned long, nbioapi_indexsearch_fp_info *, int *)


cdef InitIndexSearchEngine(NBioAPI_HANDLE hHandle):
    return NBioAPI_InitIndexSearchEngine(hHandle)


# cdef NBioAPI_RETURN TerminateIndexSearchEngine(NBioAPI_HANDLE hHandle)
#
# cdef NBioAPI_RETURN SetIndexSearchInitInfo(NBioAPI_HANDLE hHandle, NBioAPI_UINT8 nStructureType, NBioAPI_INIT_INFO_PTR pInitInfo)
#
# cdef NBioAPI_RETURN GetIndexSearchInitInfo(NBioAPI_HANDLE hHandle, NBioAPI_UINT8 nStructureType, NBioAPI_INIT_INFO_PTR pInitInfo)
#
# cdef NBioAPI_RETURN AddFIRToIndexSearchDB(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR pInputFIR, NBioAPI_UINT32 nUserID, NBioAPI_INDEXSEARCH_SAMPLE_INFO_PTR pSampleInfo)
#
# cdef NBioAPI_RETURN RemoveDataFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo)
#
# cdef NBioAPI_RETURN RemoveUserFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_UINT32 nUserID)
#
# cdef NBioAPI_RETURN IdentifyDataFromIndexSearchDB(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR pInputFIR, NBioAPI_FIR_SECURITY_LEVEL nSecuLevel, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo, NBioAPI_INDEXSEARCH_CALLBACK_INFO_PTR_0 pCallbackInfo0)
#
# cdef NBioAPI_RETURN IdentifyDataFromIndexSearchDBEx(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR pInputFIR, NBioAPI_FIR_SECURITY_LEVEL nSecuLevel, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo, NBioAPI_INDEXSEARCH_CALLBACK_INFO_PTR_0 pCallbackInfo0)
#
# cdef NBioAPI_RETURN ClearIndexSearchDB(NBioAPI_HANDLE hHandle)
#
# cdef NBioAPI_RETURN SaveIndexSearchDBToFile(NBioAPI_HANDLE hHandle, const NBioAPI_CHAR *szFilepath)
#
# cdef NBioAPI_RETURN LoadIndexSearchDBFromFile(NBioAPI_HANDLE hHandle, const NBioAPI_CHAR *szFilepath)
#
# cdef NBioAPI_RETURN GetDataCountFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_UINT32 *pDataCount)
#
# cdef NBioAPI_RETURN CheckDataExistFromIndexSearchDB(NBioAPI_HANDLE hHandle, NBioAPI_INDEXSEARCH_FP_INFO_PTR pFpInfo, NBioAPI_BOOL *pExist)
